//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App
{
    using System;
    using System.Collections.Generic;
    
    public partial class AluguerEquipamento
    {
        public Nullable<decimal> preco { get; set; }
        public int NumAluguer { get; set; }
        public int CodEquip { get; set; }
    
        public virtual Equipamento Equipamento { get; set; }
        public virtual Aluguer Aluguer { get; set; }
    }
}
