//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aluguer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Aluguer()
        {
            this.AluguerEquipamentos = new HashSet<AluguerEquipamentos>();
            this.Promocoes = new HashSet<Promocoes>();
        }
    
        public int Num { get; set; }
        public System.DateTime DataInicio { get; set; }
        public System.DateTime DataFim { get; set; }
        public int Duracao { get; set; }
        public Nullable<int> NumEmp { get; set; }
        public Nullable<int> CodCli { get; set; }
        public Nullable<int> Removido { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AluguerEquipamentos> AluguerEquipamentos { get; set; }
        public virtual Cliente Cliente { get; set; }
        public virtual Empregado Empregado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Promocoes> Promocoes { get; set; }
    }
}
