//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrecoAluguer
    {
        public System.DateTime ValidadeI { get; set; }
        public System.DateTime ValidadeF { get; set; }
        public int Duracao { get; set; }
        public Nullable<decimal> Valor { get; set; }
        public int EquipId { get; set; }
    
        public virtual Equipamentos Equipamentos { get; set; }
    }
}
